export global Theme  {

    // durations
    out property <duration> duration-fast: 100ms;
    out property <duration> duration-regular: 250ms;

    out property <length> window-width: 172px;
    out property <length> window-height: 320px;
    out property <color> window-background: #000000;

    out property <length> menu-font-size: 28px;
    out property <length> menu-item-size: 60px;
    out property <length> menu-selected-item-size: 80px;
    out property <color> menu-item-background-color: #0025FF;
    out property <color> menu-selected-item-background-color: #FFFFFF;
    out property <color> menu-item-foreground-color: #FFFFFF;
    out property <color> menu-selected-item-foreground-color: #0025FF;
    out property <color> menu-item-label-color: #FFFFFF;
    
    out property <length> menu-item-radius-regular: 12px;

    out property <length> menu-conveyer-spacing: 15px;
    out property <length> menu-conveyer-y-offset: 48px;
}